/**
 * @file system_stm32h5xx.c
 * @brief System initialization for STM32H573
 *
 * This file provides the SystemInit() function called by startup code
 * before main(). It will be populated with clock configuration code
 * generated by STM32CubeMX in Phase 1.
 *
 * Based on ST's system_stm32h5xx.c template, adapted for CRUST-y architecture.
 */

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

// Temporary definitions for compilation (will be replaced with ST CMSIS headers in Phase 1)
#ifndef __FPU_PRESENT
#define __FPU_PRESENT 1
#endif

#ifndef __FPU_USED
#define __FPU_USED 1
#endif

// Minimal SCB definition for FPU configuration (will use full CMSIS in Phase 1)
typedef struct {
    uint32_t RESERVED0[34];       // Offset 0x00-0x87
    volatile uint32_t CPACR;      // Coprocessor Access Control Register at offset 0x88
} SCB_Type;

#define SCB_BASE   0xE000ED00UL
#define SCB        ((SCB_Type *)SCB_BASE)

/**
 * @brief System Clock Frequency (will be 250 MHz after clock init)
 *
 * This variable is updated in SystemInit() and SystemCoreClockUpdate()
 * and used by HAL drivers to calculate timing.
 */
uint32_t SystemCoreClock = 64000000;  // Default: 64 MHz HSI (before PLL)

/**
 * @brief Initialize the system
 *
 * This function is called by startup code after .data/.bss initialization
 * but before calling main(). It performs:
 *   - FPU configuration
 *   - Flash prefetch and instruction cache enable
 *   - Clock system initialization (will use CubeMX-generated code)
 *   - Power regulator voltage scaling
 *
 * @note This function will be filled with STM32CubeMX-generated clock
 *       configuration code in Phase 1, Priority 3 (NEXT_SESSION.md)
 */
void SystemInit(void)
{
    /* FPU settings ------------------------------------------------------------*/
    #if (__FPU_PRESENT == 1) && (__FPU_USED == 1)
        /* Enable FPU (Cortex-M33 has FPU) */
        /* Set CP10 and CP11 Full Access */
        SCB->CPACR |= ((3UL << 10*2)|(3UL << 11*2));
    #endif

    /* NOTE: For now, running on default HSI (64 MHz)
     *
     * In Phase 1, this will be replaced with:
     *   1. Configure Flash wait states for 250 MHz
     *   2. Configure PLL (HSI 64 MHz -> 250 MHz)
     *   3. Enable instruction/data caches
     *   4. Configure voltage scaling
     *   5. Switch system clock to PLL
     *
     * Code will be adapted from STM32CubeMX output:
     *   CubeMX_Generated/Core/Src/system_stm32h5xx.c
     */

    /* TODO Phase 1: Add CubeMX-generated clock configuration here */

    /* Update SystemCoreClock variable */
    SystemCoreClock = 64000000;  /* Will be 250000000 after Phase 1 */
}

/**
 * @brief Update SystemCoreClock variable
 *
 * Updates the SystemCoreClock variable with current core clock
 * retrieved from CPU registers. Called after clock configuration changes.
 */
void SystemCoreClockUpdate(void)
{
    /* TODO Phase 1: Calculate actual system clock from RCC registers */
    /* For now, just use the default value */
    SystemCoreClock = 64000000;  /* Will calculate from RCC in Phase 1 */
}

#ifdef __cplusplus
}
#endif
